[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/status/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
[functions."update-data"]
schedule = "@daily"
[[redirects]]
from = "/api/system_status"
to = "/.netlify/functions/system-status"
status = 200
[[redirects]]
from = "/api/electricity_rates_latest.json"
to = "/.netlify/functions/electricity-rates"
status = 200
[[redirects]]
from = "/api/efficiency_all_other_costs_latest.json"
to = "/.netlify/functions/efficiency-all-other-costs"
status = 200
[[redirects]]
from = "/api/electricity_rates_latest.json"
to = "/.netlify/functions/electricity-rates"
status = 200
