[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/status/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
[functions."update-data"]
schedule = "@daily"
[[redirects]]
from = "/api/system_status"
to = "/.netlify/functions/system-status"
status = 200
[[redirects]]
from = "/api/electricity_rates_latest.json"
to = "/.netlify/functions/electricity-rates"
status = 200
[[redirects]]
from = "/api/efficiency_all_other_costs_latest.json"
to = "/.netlify/functions/efficiency-all-other-costs"
status = 200
[[redirects]]
from = "/api/electricity_rates_latest.json"
to = "/.netlify/functions/electricity-rates"
status = 200
[[redirects]]
from = "/api/heating_fuels_latest.json"
to = "/.netlify/functions/heating-fuels-latest"
status = 200
[[redirects]]
from = "/api/transportation_fuels_latest.json"
to = "/.netlify/functions/transportation-fuels-latest"
status = 200
[[redirects]]
from = "/api/energy_prices_latest.json"
to = "/.netlify/functions/energy-prices-latest"
status = 200
[[redirects]]
from = "/api/energy_prices_latest_with_fallback.json"
to = "/.netlify/functions/energy-prices-latest-with-fallback"
status = 200
[[redirects]]
from = "/api/energy_prices_latest_ui.json"
to = "/.netlify/functions/energy-prices-latest-ui"
status = 200
