[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/status/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
[functions."update-data"]
schedule = "@daily"
